### ISSUE TITLE
In Firefox 77.0.1 (64-bit) tab is not exposing the console

### ISSUE THREAD

**Issue by emibap** [benmalka/foxdriver#7] opened 2020-06-04 13:42 UTC
Hey. Sadly, after updating to FF 77 the console access seems to be broken.

Here's the code to verify it:

```
const url = 'http://www.bing.com'
const timeout = 10

import Foxdriver from '@benmalka/foxdriver'

(async () => {
    console.log('FoxDriver Visiting URL: ' + url);
    const { browser, tab } = await Foxdriver.launch({
        url: url
    });

    if (!tab.hasOwnProperty('console')) {
        console.error('FoxDriver error: Tab object not exposing console.')
        process.exit([1])
    }

    try {
        await tab.console.startListeners();
    } catch(e) {
        console.error('FoxDriver error connecting to the browser console: ' + e.toString())
        process.exit([1])
    }

    // wait until page is loaded and a timeout to get the console log
    await new Promise((resolve) => setTimeout(resolve, timeout*1000))
    // Get logs and page errors
    let logs = null
    try {
        logs = await tab.console.getCachedMessages();
    } catch(e) {
        console.error('FoxDriver error getting console messages: ' + e.toString())
        process.exit([1])
    }

    console.log('FoxDriver logs:');
    console.log(logs)
    
    // close browser
    browser.close()
    console.log('FoxDriver autoclosing after ' + process.uptime() + ' seconds');

})()
```

I tested it on Mac OS Catalina and Windows 10.

**Comment by flotwig** [comment] 2020-06-25 15:44
Having a similar issue - FF 77 64-bit on Linux, `tab.memory` is no longer available, where it was in earlier versions.

**Comment by flotwig** [comment] 2020-06-25 15:46
This seems to be the culprit @emibap: https://github.com/saucelabs/foxdriver/pull/17

**Comment by benmalka** [comment] 2020-06-28 08:42
The issue is related to the new architecture change of the Tab object. There's a backward compatibility code that checks whether it is necessary to fetch the Tab's actors (using getTarget) or not (for firefox versions < 75 ). It will be fixed today

**Comment by benmalka** [comment] 2020-06-30 07:05
#8

**Comment by benmalka** [comment] 2020-06-30 07:09
@emibap 
Please discard this block. It will always fail

if (!tab.hasOwnProperty('console')) {
        console.error('FoxDriver error: Tab object not exposing console.')
        process.exit([1])
    }

Tab object has no actual property of 'console' before it has been called.

**Comment by benmalka** [comment] 2020-06-30 07:12
v0.4.1 has been published to npm. Closing issue

**Closed as completed by benmalka** 2020-06-30 07:12 UTC

**Comment by flotwig** [comment] 2020-06-30 13:15
Thanks @benmalka
